baseURL = "https://r9y9.github.io/wavenet_vocoder/"
languageCode = "ja-jp"
title = "An open source implementation of WaveNet vocoder"
author = "Ryuichi YAMAMOTO"

[params]
  author    = "Ryuichi YAMAMOTO"
  project   = "wavenet_vocoder"
  logo      = "/images/r9y9.jpg"
  twitter   = "r9y9"
  github    = "r9y9"
  analytics = "UA-44433856-1"
